spring.application.name=task

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/Twitter_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false


spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000

#letsmakeandummystingwillbeencodedinbase46usingasciiidontgiveashitifitgetsexposed
token.signing.key=bGV0c21ha2VhbmR1bW15c3Rpbmd3aWxsYmVlbmNvZGVkaW5iYXNlNDZ1c2luZ2FzY2lpaWRvbnRnaXZlYXNoaXRpZml0Z2V0c2V4cG9zZWQ=